CREATE TABLE [dbo].[ToDoItem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[Done] [bit] NOT NULL,
 CONSTRAINT [PK_ToDoItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ToDoItem] ADD  CONSTRAINT [DF_ToDoItem_Done]  DEFAULT ((0)) FOR [Done]
GO